### ISSUE TITLE
Fix latex issues when running via WandB

### ISSUE THREAD

**Issue by Wilsker** [Wilsker/tdsm_encoder#40]

**Comment by ChenHua-Hsu** [comment]
It's just a test

**Comment by ChenHua-Hsu** [comment]
I meet the problems like the .err below
When I run sweep file, the error will show. However, the test_sweep won't show any error. 
Below are my github, the files are in the latex branch
https://github.com/ChenHua-Hsu/truobleshooting/tree/latex_problem
